//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_data
    {
        public int id { get; set; }
        public string parameter { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<int> total_frame { get; set; }
        public Nullable<int> frame_rate { get; set; }
        public Nullable<double> bitrate { get; set; }
        public Nullable<double> y_psnr { get; set; }
        public Nullable<double> u_psnr { get; set; }
        public Nullable<double> v_psnr { get; set; }
        public Nullable<double> yuv_psnr { get; set; }
        public Nullable<double> total_second { get; set; }
        public string output_image { get; set; }
        public string config_files { get; set; }
    }
}
